"""
Report Generator — Structured clinical reports using K2 Think V2.

Grounded in:
- WHO Malaria Microscopy Standard Operating Procedures (reporting format)
- Clinical pathology lab report structure (CAP guidelines)
- CDC Malaria Case Report form fields

K2 Think fills in the clinical narrative sections; the structure and
required fields are enforced by the template — not left to the LLM to improvise.
"""

import json
import logging
from datetime import datetime, timezone

logger = logging.getLogger("malariaai.reports")

# ── Standardized Report Template ────────────────────────────────
# Based on WHO microscopy reporting + clinical pathology lab reports.
# Required fields are enforced; K2 Think generates the narrative sections.

REPORT_TEMPLATE = {
    "header": {
        "report_title": "Malaria Blood Film Screening Report",
        "facility": "MalariaAI — AI-Assisted Screening Platform",
        "report_id": "",
        "patient_id": "",
        "date_collected": "",
        "date_reported": "",
        "specimen_type": "Peripheral blood film (thin smear, Giemsa-stained)",
    },
    "screening_result": {
        "classification": "",       # PARASITIZED / UNINFECTED
        "confidence_score": "",     # e.g., "92.3%"
        "confidence_level": "",     # HIGH / MODERATE / LOW / BORDERLINE
        "method": "Convolutional Neural Network (3-layer CNN, 95.43% validated accuracy on NIH dataset of 27,558 images)",
        "parasitemia_estimate": "", # If applicable
    },
    "clinical_interpretation": "",   # K2 Think generates this
    "treatment_recommendation": "",  # K2 Think generates this (grounded in RAG guidelines)
    "recommended_actions": [],       # K2 Think generates this
    "patient_guidance": "",          # K2 Think generates this
    "quality_notes": "",             # K2 Think generates this (re: confidence, image quality)
    "disclaimer": (
        "DISCLAIMER: This report was generated by an AI-assisted screening tool "
        "and does NOT constitute a medical diagnosis. The CNN model has a validated "
        "accuracy of 95.43% — meaning approximately 1 in 22 results may be incorrect. "
        "All results must be confirmed by a qualified laboratory technician or "
        "medical professional before any treatment decisions are made. "
        "In cases of clinical suspicion, treat presumptively per WHO guidelines "
        "regardless of screening result."
    ),
    "methodology": {
        "model": "3-block CNN (32→64→128 filters), trained on NIH Malaria Cell Images Dataset",
        "dataset": "27,558 cell images (13,779 parasitized + 13,779 uninfected)",
        "validation_accuracy": "95.43% on held-out test set (stratified 80/20 split)",
        "preprocessing": "Images resized to 64×64px, normalized to [0,1] range",
        "clinical_intelligence": "K2 Think V2 (MBZUAI) with RAG-retrieved WHO/CDC guidelines",
    },
}


def _confidence_level(confidence: float) -> str:
    """Map confidence score to clinical confidence level."""
    if confidence >= 0.95:
        return "HIGH"
    elif confidence >= 0.80:
        return "MODERATE"
    elif confidence >= 0.65:
        return "LOW"
    else:
        return "BORDERLINE — result unreliable, confirmatory testing required"


class ReportGenerator:
    """Generate structured clinical reports using K2 Think V2."""

    def __init__(self, k2_client):
        self.k2 = k2_client

    async def generate(
        self,
        scan_id: str,
        patient_id: str | None,
        analysis: dict,
        include_guidelines: bool = True,
    ) -> dict:
        """
        Generate a structured clinical report.
        The template enforces medical reporting standards.
        K2 Think fills the narrative sections with clinical intelligence.
        """

        patient_id = patient_id or f"PID-{scan_id}"
        now = datetime.now(timezone.utc)
        timestamp = now.isoformat()

        # Extract values from analysis
        prediction = analysis.get("prediction", "unknown").upper()
        confidence = analysis.get("confidence", 0.0)
        clinical_summary = analysis.get("clinical_summary", "")
        treatment_guidance = analysis.get("treatment_guidance", "")
        patient_education = analysis.get("patient_education", "")
        severity = analysis.get("severity_assessment", "unknown")
        guidelines_cited = analysis.get("guidelines_cited", [])

        # Ask K2 Think to generate the narrative sections using the template structure
        prompt = f"""You are writing a clinical screening report for a malaria blood film analysis. 
Fill in the following sections based on the scan results. Write in professional clinical pathology language.

SCAN RESULTS:
- Classification: {prediction}
- Confidence: {confidence:.1%} ({_confidence_level(confidence)})
- Severity Assessment: {severity}
- AI Clinical Summary: {clinical_summary}
- AI Treatment Guidance: {treatment_guidance}

Generate these specific report sections as JSON:

{{
  "clinical_interpretation": "3-4 sentences. Professional clinical interpretation of the screening result. Reference the confidence level. Note any limitations. Written as it would appear in a clinical pathology report.",
  "treatment_recommendation": "If parasitized: specific WHO-recommended treatment protocol with drug names, dosages, and duration. If uninfected: state no antimalarial treatment indicated, note conditions for re-testing. Always include confidence caveats.",
  "recommended_actions": ["List of 4-6 specific, actionable next steps for the clinician. E.g., 'Confirm result with expert microscopy (thick and thin blood film)', 'Order complete blood count (CBC)', etc."],
  "patient_guidance": "2-3 sentences in simple, clear language explaining the result to the patient and what they should do next.",
  "quality_notes": "Note on the reliability of this specific result based on confidence level. Any caveats about AI-assisted screening vs gold-standard microscopy."
}}

Return ONLY valid JSON."""

        try:
            messages = [
                {
                    "role": "system",
                    "content": (
                        "You are a clinical pathology report writer. Write precise, "
                        "professional medical language suitable for a lab report. "
                        "Cite specific guidelines (WHO, CDC) where applicable."
                    ),
                },
                {"role": "user", "content": prompt},
            ]

            raw = await self.k2._call(messages, temperature=0.1, max_tokens=4096)
            narrative = self.k2._parse_json_response(raw, {
                "clinical_interpretation": clinical_summary,
                "treatment_recommendation": treatment_guidance,
                "recommended_actions": [
                    "Confirm result with expert microscopy",
                    "Perform rapid diagnostic test (RDT) if available",
                    "Assess patient clinical status",
                ],
                "patient_guidance": patient_education,
                "quality_notes": f"Confidence level: {_confidence_level(confidence)}.",
            })
        except Exception as e:
            logger.error(f"K2 report generation failed: {e}")
            narrative = {
                "clinical_interpretation": clinical_summary or "AI analysis unavailable. Manual review required.",
                "treatment_recommendation": treatment_guidance or "Consult treating physician.",
                "recommended_actions": [
                    "Confirm result with expert microscopy (thick and thin blood film)",
                    "Perform RDT (HRP2-based for P. falciparum) if available",
                    "Complete clinical assessment of the patient",
                    "Consult treating physician for management decisions",
                ],
                "patient_guidance": patient_education or "Please follow up with your healthcare provider.",
                "quality_notes": f"AI confidence: {confidence:.1%} ({_confidence_level(confidence)}).",
            }

        # Assemble the full structured report
        report = dict(REPORT_TEMPLATE)

        # Header
        report["header"] = {
            **REPORT_TEMPLATE["header"],
            "report_id": f"MAI-{scan_id[:8].upper()}",
            "patient_id": patient_id,
            "date_collected": now.strftime("%Y-%m-%d"),
            "date_reported": now.strftime("%Y-%m-%d %H:%M UTC"),
        }

        # Screening result
        report["screening_result"] = {
            **REPORT_TEMPLATE["screening_result"],
            "classification": prediction,
            "confidence_score": f"{confidence:.1%}",
            "confidence_level": _confidence_level(confidence),
        }

        # K2 Think narrative sections
        report["clinical_interpretation"] = narrative["clinical_interpretation"]
        report["treatment_recommendation"] = narrative["treatment_recommendation"]
        report["recommended_actions"] = narrative["recommended_actions"]
        report["patient_guidance"] = narrative["patient_guidance"]
        report["quality_notes"] = narrative["quality_notes"]

        # Metadata
        report["guidelines_cited"] = guidelines_cited
        report["severity_assessment"] = severity

        return {
            "scan_id": scan_id,
            "patient_id": patient_id,
            "report": report,
            "generated_at": timestamp,
        }
